/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Open a connection. Returns a `Promise<Client>`. */
export declare function connect(url: string): Promise<Client>
/** An async database client. Returned by [`connect`]. */
export declare class Client {
  /** Run a non-row statement (INSERT/UPDATE/DDL). Resolves to rows affected. */
  execute(sql: string, params?: Array<ParamValue> | undefined | null): Promise<number>
  /**
   * Run a query. Resolves to a `Buffer` holding the NCB columnar payload,
   * which `decodeBatch()` in the TS wrapper turns into zero-copy typed
   * arrays. The `Vec<u8>` is transferred to V8 as an external buffer.
   */
  query(sql: string, params?: Array<ParamValue> | undefined | null): Promise<Buffer>
}
